CONFIG_POWEROFF=y
CONFIG_PM_DEVICE=y
CONFIG_PM=y
CONFIG_PM_POLICY_DEFAULT=y

CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=3072
CONFIG_BT_RX_STACK_SIZE=3072
CONFIG_HEAP_MEM_POOL_SIZE=16384

CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_I2C=y

CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVERS=y

CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_LFN=y
CONFIG_FS_FATFS_LFN_MODE_BSS=y
CONFIG_FS_FATFS_MAX_LFN=255
CONFIG_FS_FATFS_HAS_RTC=y
CONFIG_SDHC=y
CONFIG_SPI_SDHC=y

CONFIG_LOG=y
CONFIG_PRINTK=y
CONFIG_LOG_DEFAULT_LEVEL=1
CONFIG_LOG_BACKEND_UART_AUTOSTART=y

# Silence noisy subsystems, keep main errors visible
CONFIG_BT_LOG_LEVEL_ERR=y
CONFIG_BT_HCI_DRIVER_LOG_LEVEL_ERR=y
CONFIG_DISK_LOG_LEVEL_ERR=y
CONFIG_FS_LOG_LEVEL_ERR=y
CONFIG_SPI_LOG_LEVEL_ERR=y
CONFIG_I2C_LOG_LEVEL_ERR=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_LINE_CTRL=y
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_UDC_BUF_COUNT=16
CONFIG_UDC_BUF_POOL_SIZE=8192
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y
CONFIG_USBD_CDC_ACM_LOG_LEVEL_OFF=y
CONFIG_CDC_ACM_SERIAL_PRODUCT_STRING="datalogger_rev1"
CONFIG_CDC_ACM_SERIAL_PID=0x0004

CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_OBSERVER=y
CONFIG_BT_MAX_CONN=4
CONFIG_BT_DEVICE_NAME="sensor_datalogger"
CONFIG_BT_GATT_CLIENT=y

CONFIG_BT_USER_DATA_LEN_UPDATE=y
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_L2CAP_TX_MTU=247

CONFIG_BT_L2CAP_TX_BUF_COUNT=20
CONFIG_BT_BUF_ACL_TX_COUNT=20
CONFIG_BT_BUF_EVT_RX_COUNT=24
