CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_UDC_BUF_COUNT=16
CONFIG_UDC_BUF_POOL_SIZE=8192
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y
CONFIG_USBD_CDC_ACM_LOG_LEVEL_OFF=y
CONFIG_CDC_ACM_SERIAL_PRODUCT_STRING="datalogger_rev1"
CONFIG_CDC_ACM_SERIAL_PID=0x0004